### ISSUE TITLE
Getting registry errors when I open a .CFM file in Atom

### ISSUE THREAD

**Issue by dkh7m** [ditinc/linter-cflint#19]
I get the following errors in the Atom debugger when I open a .CFM file. I have JRE and JDK installed and have the JAVA_HOME path set in my variables. 

/C:/Users/[user]/.atom/packages/linter-cflint/lib/main.js:151 Error: Command failed: reg query "hklm\software\javasoft\java development kit"
ERROR: The system was unable to find the specified registry key or value.

Error: Command failed: reg query "hklm\software\wow6432node\javasoft\java development kit"
ERROR: The system was unable to find the specified registry key or value.
(anonymous function) @ /C:/Users/[user]/.atom/packages/linter-cflint/lib/main.js:151

**Comment by clang676** [comment]
Hey @dkh7m did you ever figure out a way to correct this problem?

**Comment by sjmatta** [comment]
I believe this is fixed in the latest version of find-java-home, which linter-cflint is using: https://github.com/jsdevel/node-find-java-home/pull/12

I'll update the dependency.

**Comment by sjmatta** [comment]
Should be resolved in the latest release. Sorry for the delay.

**Comment by dkh7m** [comment]
Thanks! I haven’t checked yet but will today.

On Dec 7, 2016, at 8:07 AM, Stephen Matta <notifications@github.com<mailto:notifications@github.com>> wrote:


Should be resolved in the latest release. Sorry for the delay.
