### ISSUE TITLE
An unexpected error occured with linter-cflint. See the debug log for details

### ISSUE THREAD

**Issue by clang676** [ditinc/linter-cflint#20]
Any time i go to cold fusion files this error is shown in ATOM, My java path is C:\Program Files\Java\jre1.8.0_111\bin, could that be the problem?

Console error:
main.js:123 
Error: Command failed: reg query "hklm\software\javasoft\java development kit"
ERROR: The system was unable to find the specified registry key or value.

Error: Command failed: reg query "hklm\software\wow6432node\javasoft\java development kit"
ERROR: The system was unable to find the specified registry key or value.

**Comment by sjmatta** [comment]
Same as #19
