### ISSUE TITLE
Do not use execSync

### ISSUE THREAD

**Issue by steelbrain** [ditinc/linter-cflint#3]
It's a bad practice because `execSync` blocks the event loop completely until the child process is completed, linter's API allows you to return a promise and resolve it with results, You could use that.

**Comment by sjmatta** [comment]
Thanks! It seems to work a lot smoother now.

**Comment by steelbrain** [comment]
Side note: You can use `Helpers::exec` instead of adding a completely new dependency, also it provides a nicer API. and by helper I mean the `atom-linter` npm module

**Comment by sjmatta** [comment]
I appreciate the feedback! I reduced the external dependencies and used `atom-linter` instead.

**Comment by steelbrain** [comment]
Also, I am afraid you are not using `atom-package-deps` correctly, You are supposed to add both of  those deps to your package manifest (aka `package.json`) and then call `atom-package-deps::install` using current package's name only once, which would look like `require('atom-package-deps').install('linter-cflint')`

**Comment by sjmatta** [comment]
Thanks for your help- I think I have it correct now.
