### ISSUE TITLE
Remove need for separate download of CFLint.jar

### ISSUE THREAD

**Issue by sjmatta** [ditinc/linter-cflint#8]
I need to investigate whether this can be done through the central Maven repo, but until then, at least bundle the correct CFLint.jar.

**Comment by sjmatta** [comment]
This will remove the need for the configuration item as well

**Comment by ryaneberly** [comment]
We are looking at publishing CFLint on ForgeBox - the should meet this requirement.

https://github.com/cflint/CFLint/issues/310
